# This is a basic workflow to help you get started with Actions

name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://34.95.244.247:8080"
        user: "pgurjao"
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "current_job"
